### ISSUE TITLE
Epoptes documentation needs finishing

### ISSUE THREAD

**Issue by gbaman** [RaspberryPi-LTSP/RaspberryPi-LTSP-Documentation#1]

**Comment by rypi17** [comment]
@gbaman can you send me a draft ------Email address removed-----

**Comment by gbaman** [comment]
It is very far from finished. Epoptes once installed (which is pretty simple) is rather easy to use? Not all the features work (mainly screen broadcasting) but blanking kids screens, rebooting and shutting down Pis plus also seeing the kids screens all works? There is no setup once installed via Raspi-LTSP, it should just work?
